language: python
sudo: required
dist: xenial
python:
  - "3.7"
cache:
  pip: true
env:
  global:
    - BUILD_PATH=gh-pages-build
install:
  - pip install -U pip setuptools wheel
  - pip install -r requirements.txt
script:
  - make html
  - mkdir -p ${BUILD_PATH}
  - cp -Rv build/* $BUILD_PATH
deploy:
  provider: pages
  local-dir: $BUILD_PATH
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: urbanotopus.vanille.bid
  keep-history: true
  on:
    branch: master
  edge:
    branch: v1.8.47
